ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'DEACTIVE';
ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'DONATED';
ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'MISSING';
ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'ON_SALE';
ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'REPARING';
ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'SCRAP';
